blog/blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/',include('posts.urls')),
    path('users/',include('users.urls'))
]

if settings.DEBUG:
    # urlpatterns +=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/posts/urls.py
from django.urls import path
from posts.views import PostView,PostDetail,CreatePostView,WeeklyPopularPosts,MonthlyPopularPosts, \
RecommendedPostsView,PopularPostsView

app_name='posts'
urlpatterns = [
    path('list/',PostView.as_view(),name='post_list'),
    path('<int:pk>/',PostDetail.as_view(),name='post_detail'),
    path('create/',CreatePostView.as_view(),name='post_create'),
    path('weekend/',WeeklyPopularPosts.as_view(),name='weekend'),
    path('month/',MonthlyPopularPosts.as_view(),name='month'),
    path('recommended/',RecommendedPostsView.as_view(),name='recommended'),
    path('popular/',PopularPostsView.as_view(),name='popular')

]

blog/users/urls.py
from django.urls import path
from users.views import RegisterView,LoginView,LogOutView

app_name='users'
urlpatterns = [
    path('register/',RegisterView.as_view(),name='register'),
    path('login/',LoginView.as_view(),name='login'),
    path('logout/',LogOutView.as_view(),name='logout')
]

blog/posts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.query import QuerySet
from django.utils import timezone
from hitcount.models import HitCountMixin
from django.contrib.contenttypes.fields import GenericRelation,GenericForeignKey
# Create your models here.


class VerifiedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.Verified)

class NotVerifiedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.NotVerified)
    
class RecommendedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Recommendation.Recommended)

class NotRecommendedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Recommendation.NotRecommended)

class Post(models.Model, HitCountMixin):

    class Status(models.TextChoices):
        Verified = 'VD', 'Verified'
        NotVerified = 'NV', 'NotVerified'
    
    class Recommendation(models.TextChoices):
        Recommended = 'RCMD', 'Recommended'
        NotRecommended = 'NCMD', 'NotRecommended'

    author = models.ForeignKey(User, on_delete=models.CASCADE,related_name='author')
    picture = models.ImageField(null=True, blank=True)       
    title = models.CharField(max_length=300)
    text = models.TextField()
    tags = models.ManyToManyField('Tag', blank=True) 
    publish_time = models.DateTimeField(default=timezone.now)
    viewers = models.ManyToManyField(User, blank=True,related_name='viewers') 
    status = models.CharField(max_length=2, choices=Status.choices, default=Status.NotVerified)
    recommendation = models.CharField(max_length=4, choices=Recommendation.choices, default=Recommendation.NotRecommended)   
    objects = models.Manager()
    verified = VerifiedManager()
    notverified = NotVerifiedManager()
    recommended = RecommendedManager()
    notrecommended = NotRecommendedManager()

    class Meta:
        ordering = ['-publish_time']

    def str(self):
        return self.title


class Tag(models.Model):
    name = models.CharField(max_length=50)
    
    def __str__(self):
        return self.name

class Comment(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name='comments')
    author = models.ForeignKey(User,on_delete=models.CASCADE,related_name='comments')
    text = models.TextField()
    created_time = models.DateTimeField(default=timezone.now)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['-created_time']
    
    def __str__(self):
        return self.text

blog/posts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.mail import send_mail
from posts.models import Post,Comment, Tag

class PostCreateForm(forms.ModelForm):
    tags = forms.SelectMultiple(choices=Tag.objects.all())
    class Meta:
        model = Post
        fields = ['picture','title','text','tags']
        

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

class TagCreateForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = ('name', )



blog/posts/views.py
from django.shortcuts import render,redirect,get_object_or_404
from posts.models import Post,Comment,Tag
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from posts.forms import PostCreateForm,CommentForm,TagCreateForm
from django.urls import reverse
from hitcount.views import HitCountDetailView,HitCountMixin
from hitcount.models import HitCount
from hitcount.utils import get_hitcount_model
from django.utils import timezone
from datetime import timedelta
from django.core.paginator import Paginator
from django.http import HttpResponse

# Create your views here.

from datetime import datetime

# Example ISO 8601 formatted string
iso_string = "2022-01-15T15:30:00"

# Create a datetime object from the ISO 8601 formatted string
dt_object = datetime.fromisoformat(iso_string)


class PostView(View):
    model  = Post
    count_hit = False

    def get(self,request):
        post_list = Post.objects.filter(status=Post.Status.Verified).order_by('id')
        search_query = request.GET.get('q','')
        if search_query:
            post_list = post_list.filter(title__icontains=search_query)

        paginator = Paginator(post_list,2)
        page_num = request.GET.get('page',2)
        page_obj = paginator.get_page(page_num)

        context = {
            'page_obj':page_obj,
            'search_query':search_query,
    
        }
        return render(request,'posts/postList.html',context)

class PostDetail(HitCountDetailView,View):
    model = Post    
    count_hit = True
    template_name = 'posts/postDetail.html'

    def get(self,request,pk):
        post = get_object_or_404(Post,id=pk,status=Post.Status.Verified)
        comments = post.comments.filter(active=True)
        comment_form = CommentForm()
        if request.user != post.author:
            if request.user not in post.viewers.all():
                post.viewers.add(request.user)
                post.save()
                
        context = {
            'post':post,
            'comments':comments,
            'comment_form':comment_form
        }
        return render(request,'posts/postDetail.html',context)

    def post(self,request,pk): # Posting comments
        post = Post.objects.get(id=pk)
        comment_form = CommentForm(data=request.POST)
        comments = post.comments.filter(active=True)
        if comment_form.is_valid():
            Comment.objects.create(
               post = post,
               author = request.user,
               text = comment_form.cleaned_data['text']               
           )
            comment_form = CommentForm()

        else:
            comment_form = CommentForm(data=request.POST)

        context = {
            'post':post,
            'comments':comments,
            'comment_form':comment_form
        }    
        return render(request,'posts/postDetail.html',context)

class WeeklyPopularPosts(View):

    def get(self,request):
        
        posts_list = Post.objects.filter(status=Post.Status.Verified).order_by('id')
        if posts_list:
            start_time = (timezone.now() - timedelta(days=7))
            posts_list = Post.objects.filter(publish_time__gt=start_time,status=Post.Status.Verified).order_by('hit_count_generic')
            search_query = request.GET.get('q','')
            if search_query:
                posts_list = posts_list.filter(title__icontains=search_query)
            
            paginator = Paginator(posts_list,2)
            page_num = request.GET.get('page',1)
            page_obj = paginator.get_page(page_num)

            context = {
                'posts_lists':posts_list,
                'page_obj':page_obj,
                'search_query':search_query
            }

            return render(request,'posts/week.html',context)
        else:
            return HttpResponse("No posts found")   

class MonthlyPopularPosts(View):

    def get(self,request):
        post_list = Post.objects.filter(status=Post.Status.Verified).order_by('id')
        if post_list:   
            start_time = timezone.now() - timedelta(days=30)
            post_list = post_list.filter(publish_time__gt=start_time).order_by('hit_count_generic')
            search_query = request.GET.get('q','')
            if search_query:
                post_list = post_list.filter(title__icontains=search_query)
                
            paginator = Paginator(post_list,2)
            page_num = request.GET.get('page',1)
            page_obj = paginator.get_page(page_num)

            context = {
                'page_obj':page_obj,
                'search_query':search_query
                }
            return render(request,'posts/month.html',context)
        else:
            return HttpResponse("no posts found")
class RecommendedPostsView(View):
    
    def get(self,request):
        post_list = Post.objects.filter(status=Post.Status.Verified,recommendation=Post.Recommendation.Recommended).order_by('id')
        if post_list:
            search_query = request.GET.get('q','')
            if search_query:
                post_list = post_list.filter(title__icontains=search_query)
            
            paginator = Paginator(post_list,2)
            page_num = request.GET.get('page',1)
            page_obj = paginator.get_page(page_num)

            context = {
                'page_obj':page_obj,
                'search_query':search_query
            }

            return render(request,'posts/recommended.html',context)
        else:
            return HttpResponse("No posts found")
        
class PopularPostsView(View):

    def get(self,request):
        post_list = Post.objects.filter(status=Post.Status.Verified).order_by('-viewers')
        if post_list:
        # q
            search_query = request.GET.get('q','')
            if search_query:
                post_list = Post.objects.filter(title__icontains=search_query)  
            # paginator objects
            paginator = Paginator(post_list,2)
            page_num = request.GET.get('page',1)
            page_obj = paginator.get_page(page_num)
        else: 
            return HttpResponse("No post found")
        context = {
            'search_query':search_query,
            'page_obj':page_obj
        }
        return render(request,'posts/popular.html',context)
    

class CreatePostView(LoginRequiredMixin,View):

    def get(self,request):
        form = PostCreateForm()
        tag_form = TagCreateForm()
        context = {
            'form':form,
            'tag_form': tag_form
        }
        return render(request,'posts/postCreate.html',context)

    def post(self,request):
        form = PostCreateForm(data=request.POST,files=request.FILES)
        tag_form = TagCreateForm(data=request.POST)
        if tag_form.is_valid():
            Tag.objects.create(
                name = tag_form.cleaned_data['name']
            )
            tag_form = TagCreateForm()
        else: 
            tag_form = TagCreateForm(data=request.POST)
        if form.is_valid():
            new = Post.objects.create(
                author = request.user,
                title = form.cleaned_data['title'],
                picture = form.cleaned_data['picture'],
                text = form.cleaned_data['text']
            )
            new.tags.set(form.cleaned_data['tags'])
            return redirect('posts:post_list')
        else:
            form = PostCreateForm(data=request.POST,files=request.FILES)
        context = {
            'form': form,
            'tag_form': tag_form
        }
        return render(request,'posts/postCreate.html',context)

blog/templates/posts/month.html
{% load hitcount_tags %}
<html>
    <head>
        <title>
            Month's popular posts
        </title>
    </head>
    <body>
        <div>
            <!-- Search -->
            <div>
                <form method="get">
                    <input type="text" placeholder="Search" name="q" value="{{ search_query }}">
                    <button>Search</button>
                </form>
            </div>      
            <!-- Posts -->
            <h4>Page: {{ page_obj.number }}</h4>
            {% for post in page_obj %}
            <a href="{% url 'posts:post_detail' post.pk %}"><h2>{{ post.title }}</h2></a>
            <h4>Views: {{ post.hit_count.hits }}</h4>
            {% if post.picture %}
                <img src="{{ post.picture.url }}" alt="There is a image">
            {% endif %}
            <h4>{{ post.text }}</h4>
            {% endfor %}

            <!-- Paginator links -->
            <div>
                {% if page_obj.has_previous %}
                <span><a href="?page=1">First page</a></span>
                <span><a href="{% url 'posts:month' %}?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a></span>
                {% endif %}
                <span><a href="{% url 'posts:month' %}?page={{ page_obj.number }}">{{ page_obj.number }}</a></span>
                {% if page_obj.has_next %}
                <span><a href="{% url 'posts:month' %}?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a></span>
                <span><a href="{% url 'posts:month' %}?page={{ page_obj.pagintator.num_pages }}">Last page</a></span>
                {% endif %}
            </div>
        </div>
    </body>
</html>

blog/templates/posts/popular.html
{% load hitcount_tags %}
<html>
    <head>
        <title>Popular Posts</title>
    </head>
    <body>
        {% if page_obj %}
        <!-- Search -->
        <div>
            <form method="get">
                <input type="text" placeholder="Search" name="q" value="{{ search_query }}">
                <button>Search</button>
            </form>
        </div>
        <!-- Post objects list -->
        <div>
            {% for post in page_obj %}        
                <a href="{% url 'posts:post_detail' post.pk %}"><h2>{{ post.title }}</h2></a>
                <p>Seen: {{ post.hit_count.hits }}</p>
                <p>{{ post.text }}</p>
                <p>Published at {{ post.publish_time }}</p>     
                {% if post.picture %}
                    <img src="{{ post.picture.url }}" alt="There is a image">
                {% endif %}
                <h4>{{ post.body }}</h4>
            {% endfor %}
        </div>
        <!-- Pagination links -->
        <div>
            <span><a href="?page=1">First page</a></span>
            {% if page_obj.has_previous %}
            <span><a href="{% url 'posts:post_list' %}?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a></span>
            {% endif %} 
            <span><a href="{% url 'posts:post_list' %}?page={{ page_obj.number }}">{{ page_obj.number }}</a></span>
            {% if page_obj.has_next %}
            <span><a href="{% url 'posts:post_list' %}?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a></span>
            {% endif %}
            <span><a href="{% url 'posts:post_list' %}?page={{ page_obj.paginator.num_pages }}">Last page</a></span>
        </div>
        {% else %}
        No posts found
        {% endif %}
    </body>
</html>

blog/templates/posts/postCreate.html
<html>
    <head>
        <title>Create Post</title>
    </head>
    <body>
        <div>
            <form method="post" enctype="multipart/form-data">{% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Create</button>
            </form>
        </div>
        <div>
            <form method="post">{% csrf_token %}
                {{ tag_form.as_p }}
                <button>Add tag</button>
            </form>
        </div>
    </body>
</html>

blog/templates/posts/postDetail.html
{% load hitcount_tags %}
<html>
    <head>
        <title>{{ post.title }}</title>
    </head>
    <body>
        <h4>{{ post.title }}</h4>        
        <h4>Seen: {% get_hit_count for  post %}</h4>
        <h4>Views: {{ post.views }}</h4>
        <h4>Prosmotr: {{ post.viewers.count }}</h4>
        {% if post.picture %}
            <img src="{{ post.picture.url }}" alt="There is a image">
        {% endif %}
        <h5>{{ post.text }}</h5>
        <form method="post">{% csrf_token %}
            {{ comment_form.as_p }}
            <button type="submit">Submit</button>
        </form>
        <div>
        {% for comment in comments %}
        <h4>{{ comment.author.username }}</h4>
        <h6>{{ comment.text }}</h6>
        {% endfor %}
        </div>
    </body>
</html>

blog/templates/posts/postList.html
<html>
    <head>
        <title>Posts List</title>
    </head>
    <body>
        {% if page_obj %}
            {% if messages %}
            {% for message in messages %}
            <h2>{{ message }}</h2>
            {% endfor %}
            {% endif %}
            <h4><a href="{% url 'users:register' %}">register</a></h4> 
            <h4><a href="{% url 'users:login' %}">login</a></h4>
            {% if request.user.is_authenticated %}
            <h4><a href="{% url 'users:logout' %}">logout</a></h4>
            {% endif %}
            <h4><a href="{% url 'posts:post_create' %}">create</a></h4>
            <br>
            <div>
            <span><a href="{% url 'posts:weekend' %}">Weekend</a></span>  /
            <span><a href="{% url 'posts:month' %}">Month</a></span>  /
            <span><a href="{% url 'posts:recommended' %}">Recommended</a></span>  /
            <span><a href="{% url 'posts:popular' %}">Popular</a></span>
            </div> 
            <hr>
            <div>
                <form class="d-flex" method="get">
                    <input class="form-control" type="text" placeholder="Search" name="q" value="{{ search_query }}">
                    <button class="btn btn-success">Search</button>
                </form>
            </div>      
            {% for post in page_obj %}
                {% if post.picture %}
                    <img src="{{ post.picture.url }}" alt="There is a image">
                {% endif %}
            <a href="{% url 'posts:post_detail' post.pk %}"><h4>{{ post.title }}</h4></a>
            <p>{{ post.text }}</p>
            <p>{{ post.publish_time }}</p>
            {% for tag in post.tags.all %}
            <a href="{% url 'posts:post_list' %}?q={{tag.name}}">#{{ tag.name }}</a>
            {% endfor %} <br>
            {% endfor %}
            <span><a href="?page=1">First page</a></span>
            {% if page_obj.has_previous %}
            <span><a href="{% url 'posts:post_list' %}?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a></span>
            {% endif %} 
            <span><a href="{% url 'posts:post_list' %}?page={{ page_obj.number }}">{{ page_obj.number }}</a></span>
            {% if page_obj.has_next %}
            <span><a href="{% url 'posts:post_list' %}?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a></span>
            {% endif %}
            <span><a href="{% url 'posts:post_list' %}?page={{ page_obj.paginator.num_pages }}">Last page</a></span>
        {% else %}
        <h2>No posts found</h2>
        {% endif %}
    </body>
</html>

blog/templates/posts/recommended.html
{% load hitcount_tags %}
<html>
    <head>
        <title>Recommended Posts</title>
    </head>
    <body>
        {% if page_obj %}
        <!-- Search form -->
        <div>
            <form method="get">
                <input type="text" placeholder="Search" name='q' value="{{ search_query }}" >
                <button type="butotn">Search</button>
            </form>
        </div>
        <!--  Post objects list  -->
        <div>
            {% for post in page_obj %}
            <a href="{% url 'posts:post_detail' post.pk %}"><h2>{{ post.title }}</h2></a>
            <h4>{{ post.hit_count.hits }}</h4>
            {% if post.picture %}
                <img src="{{ post.picture.url }}" alt="There is a image">
            {% endif %}
            <h4>{{ post.text }}</h4>
            <p>{{ post.publish_time }}</p>
            {% endfor %}
        </div>
        <!-- paginator links -->
        <div>
            {% if page_obj.has_previous %}            
            <span><a href="?page=1">First page</a></span>
            <span><a href="{% url 'posts:recommended' %}?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a></span>
            {% endif %}
            <span><a href="{% url 'posts:recommended' %}?page={{ page_obj.number }}">{{ page_obj.number }}</a></span>
            {% if page_obj.has_next %}
            <span><a href="{% url 'posts:recommended' %}?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a></span>
            <span><a href="{% url 'posts:recommended' %}?page={{ page_obj.paginator.num_pages }}">Last page</a></span>
            {% endif %}
        </div>
        {% else %}
        No posts found
        {% endif %}
    </body>
</html>

blog/templates/posts/week.html
{% load hitcount_tags %}
<html>
    <head>
        <title>Famous</title>
    </head>
    <body>
        <div>
            <form class="d-flex" method="get">
                <input class="form-control" type="text" placeholder="Search" name="q" value="{{ search_query }}">
                <button class="btn btn-success">Search</button>
            </form>
        </div>

        {% for post in page_obj %}
        <a href="{% url 'posts:post_detail' post.pk %}"><h4>{{post.title}}</h4></a>
        {% if post.picture %}
            <img src="{{ post.picture.url }}" alt="There is a image">
        {% endif %}
        <p>Seen:{{ post.hit_count.hits }}</p>
        <h4>{{post.text}} </h4>
        {% endfor %}

        {% if page_obj.has_previous %}
        <span><a href="?page=1">First page</a></span>        
        <span><a href="{% url 'posts:weekend' %}?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a></span>
        {% endif %} 

        <span><a href="{% url 'posts:weekend' %}?page={{ page_obj.number }}">{{ page_obj.number }}</a></span>

        {% if page_obj.has_next %}
        <span><a href="{% url 'posts:weekend' %}?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a></span>
        <span><a href="{% url 'posts:weekend' %}?page={{ page_obj.paginator.num_pages }}">Last page</a></span>
        {% endif %}
    </body>
</html>